---
title: "About"
---

### Education
**[Columbia University Mailman School of Public Health](https://www.mailman.columbia.edu/)**, New York, NY		   	     
*September 2017 – (Expected) May 2019* 

**Master of Public Health (MPH) in Epidemiology**, *Certificate in Applied Biostatistics*

- Relevant Coursework: Cancer Epidemiology (Fall 2018); Pharmacoepidemiology (Fall 2018); Data Science (Fall 2018); Epidemiology I-III; Analysis of Categorical Data (Spring 2018); US Health Systems (Fall 2017)

- Thesis: *The Role of Gut Microbiota on CpG Island Methylation Phenotype CIMP Colorectal Cancer Tumorigenesis*

- Graduate Teaching Assistant: Relational Databases and SQL for Research and Data Coordination (Fall 2018)

- Leadership: Healthcare Data Analytics Club at Mailman SPH, Co-President 2018 

**[University of Florida, College of Liberal Arts and Sciences](http://www.ufl.edu/)**, Gainesville, FL	*08/2013 - 05/2017*

**Bachelor of Science in Microbiology and Cell Sciences**, *Minors in Public Health and Health Disparities in Society*

- Relevant Coursework: Python for Biologists; Molecular Biology; Genetics; Advanced Microbiology Lab

### Public Health Experience 

**[Center for Infection and Immunity: Chronic Diseases](https://www.mailman.columbia.edu/research/center-infection-and-immunity)**, Columbia SPH, Research Asst., New York, NY    
*January 2018 – Present*

- Supports PI by generating analyses of clinical, genetic, and metagenomics data from biobanks and patient samples to investigate the gut microbiome as a factor in biomarker-specific breast and colorectal cancers.
- Creates efficiencies by writing data cleanings scripts to perform tasks collaborators had previously done by hand.
- Leverages cross function knowledge in cell biology, epidemiology, and analytics methods to serve as a liaison between content expert, bioinformatician, study coordinator, and laboratory technician.
•	Manages complex, data and generates reproducible reports and visualizations with R, R Markdown, and Github.

**[AbbVie Inc., R&D, Development Design Center](https://stories.abbvie.com/stories/clinical-trials-millennial-style.htm)**, Graduate Intern, Lake Forrest, IL            	       	        
*May 2018 – August 2018*

- Applied epidemiologic methods to systematically review and critique data sources for sources of invalidity or biases; developed a novel approach for answering research question when original data sources and methods quality standards.  
- Curated real world data from recent cancer clinic trials by querying several private and public databases, critiqued data for potential biases, and implemented observational research methods to meet business need.
- Communicated findings to diverse audiences through interactive presentations, posters, and data visualizations.
- Systematically reviewed quantitative and qualitative literature regarding barriers to participating in clinical trials for cancer patients to inform internal consultant teams about current body of literature regarding patient-centric trial design.

**[WellFlorida Council HIV Prevention Program](https://wellflorida.org/blog/high-impact-prevention-hip/)**, Practicum Student, Greater Gainesville, FL  	        
*September 2016 – December 2016*

- Worked with community members and advocates to bring access to HIV testing to high-risk populations.
- Used clear and simple language to educate community members about safe-sex practices at outreach events.

**[UF College of Medicine, Department of Cell Biology](https://acb.med.ufl.edu/)**, Research Assistant, Gainesville, FL		        
*August 2014 – September 2015*

- Collaborated with a PI to analyze the effect of anti-cancer drugs on tumor cell lines with light microscopy.
- Compiled data from in vitro drug studies, quantified cellular mechanisms, and created data visualizations. 

**[HealthStreet, UF Department of Epidemiology](http://healthstreet.program.ufl.edu/)**, Intern, Gainesville, FL 			      	        
*May 2015 – July 2015*

- Assisted health workers in linking underrepresented community members to local, relevant clinical trials, and helped refer patients to medical or social services to support their participation in clinical research. 
- Aided community health workers in assessing the readability of patient education materials. 

### Skills
**Statistical Programming Languages:** SQL/MySQL, R, R Markdown, Github, SAS, Python (basic), Microsoft Access& Excel

### Community Involvement
**Children’s Miracle Network Hospital Dance Marathon:** 4+ years of involvement in large-scale philanthropies for local children’s hospitals, including Data Strategist and Dir. of Recruitment for [The Stand NYC Dance Matahon](http://www.dmstandnyc.org/), and Asst. Dir. of Community Outreach for [Dance Marathon at UF](http://floridadm.org/).
